### ISSUE TITLE
can you add a licence ? 

### ISSUE THREAD

**Issue by jediofgever** [milvusrobotics/mrp2_simulator#5]
HI,
Thanks for making this open. I would like to use this repo in my project. I would like to know under what license this project  has been published. 

Thank you !

**Comment by incebellipipo** [comment]
Licenses defined package wise in ROS. We might need to add LICENSE.md for clarification to the whole repo. We are currently working on a release for all mrp2 packages and make it available global ROS apt repository. You can see the licenses below:

https://github.com/milvusrobotics/mrp2_simulator/blob/884fed8a8ba263bddb44b9bee32df6c945056eb0/mrp2_gazebo/package.xml#L7

https://github.com/milvusrobotics/mrp2_simulator/blob/884fed8a8ba263bddb44b9bee32df6c945056eb0/mrp2_simulator/package.xml#L7

@OnurDz what do you think about adding LICENSE.md in root of the package?

**Comment by OnurDz** [comment]
I'll be happy to work on it next week when I get back to office.

**Comment by OnurDz** [comment]
Created LICENCE.md in 0cef15afe626ec65c9a2bb2422b9b67968fdeb7f
Closing the issue.
